### ISSUE TITLE
Type mismatch: inferred type is Any? but Any was expected

### ISSUE THREAD

**Issue by blackbirdsr71br** [svenjacobs/reveal#27] opened 2023-02-23 23:29 UTC
internal companion object {

		internal fun newSaver(keySaver: Saver<Key, Any>): Saver<RevealState, *> = listSaver(
			save = {
				listOf(
					it.isVisible,
					it.currentRevealableKey?.let {key -> with(keySaver) {save(key)}}
				)
			},
			restore = {
				RevealState(
					visible = it[0] as Boolean,
					restoreCurrentRevealableKey = it[1]?.let { keySaveable ->
						keySaver.restore(keySaveable)
					},
				)
			},
		)
	}

Good afternoon, this solution is very good, only when implementing the code in my app I get this error which I don't understand why, what would be the version of jetpack compose that is required?, or if there is something wrong
Help, Please

**Comment by svenjacobs** [comment] 2023-02-24 05:03
Where exactly do you get this error (which line) and which Compose version are you using?

**Comment by svenjacobs** [comment] 2023-03-08 18:23
@blackbirdsr71br Please provide some more information and code to reproduce the issue or else I will have to close the issue because I don't know how to reproduce this.

**Closed** 2023-03-21 13:56 UTC
Labels: question
