### ISSUE TITLE
Support for auto-scrolling when coach mark items are off the screen in Scrollable composable (LazyColumn, LazyRow, LazyGrid

### ISSUE THREAD

**Issue by blackbirdsr71br** [svenjacobs/reveal#52] opened 2023-07-10 23:12 UTC
The error occurs when the composable is in a LazyColumn or LazyRow and does not have focus on the screen, if there are 5 components and the fifth is not visible in the LazyColumn, the application crashes, I attach an example video and android project

https://github.com/svenjacobs/reveal/assets/24237848/dcb67a0a-19e9-443b-a6c2-d2654e7ec750

[CoachMarkDemo.zip](https://github.com/svenjacobs/reveal/files/12009210/CoachMarkDemo.zip)

**Comment by svenjacobs** [comment] 2023-07-17 08:52
Thanks for the video and sample project. However I'm going to close this issue because it's a duplicate of #48

**Closed by svenjacobs** 2023-07-17 08:52 UTC
